version: '3.9'

services:
  # ============ MYSQL SHARD 1 ============
  mysql_shard1_master:
    image: mysql:latest
    container_name: mysql_shard1_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command: --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard1_master_data:/var/lib/mysql

  mysql_shard1_slave1:
    image: mysql:latest
    container_name: mysql_shard1_slave1
    depends_on:
      - mysql_shard1_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    command: --server-id=2
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard1_slave1_data:/var/lib/mysql

  mysql_shard1_slave2:
    image: mysql:latest
    container_name: mysql_shard1_slave2
    depends_on:
      - mysql_shard1_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    command: --server-id=3
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard1_slave2_data:/var/lib/mysql

  # ============ MYSQL SHARD 2 ============

  mysql_shard2_master:
    image: mysql:latest
    container_name: mysql_shard2_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3309:3306"
    command: --server-id=11
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard2_master_data:/var/lib/mysql

  mysql_shard2_slave1:
    image: mysql:latest
    container_name: mysql_shard2_slave1
    depends_on:
      - mysql_shard2_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
    command: --server-id=12
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard2_slave1_data:/var/lib/mysql

  mysql_shard2_slave2:
    image: mysql:latest
    container_name: mysql_shard2_slave2
    depends_on:
      - mysql_shard2_master
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SHARD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3311:3306"
    command: --server-id=13
      --relay-log=relay-bin
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    volumes:
      - ./shard2_slave2_data:/var/lib/mysql

  # ============ POSTGRESQL SHARD 1 ============
  postgres_shard1_primary:
    image: bitnami/postgresql:14
    container_name: postgres_shard1_primary
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_SHARD}
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard1_primary_data:/bitnami/postgresql

  postgres_shard1_replica1:
    image: bitnami/postgresql:14
    container_name: postgres_shard1_replica1
    ports:
      - "5433:5432"
    depends_on:
      - postgres_shard1_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgres_shard1_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard1_replica1_data:/bitnami/postgresql

  postgres_shard1_replica2:
    image: bitnami/postgresql:14
    container_name: postgres_shard1_replica2
    ports:
      - "5434:5432"
    depends_on:
      - postgres_shard1_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgres_shard1_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard1_replica2_data:/bitnami/postgresql

  # ============ POSTGRESQL SHARD 2 ============
  postgres_shard2_primary:
    image: bitnami/postgresql:14
    container_name: postgres_shard2_primary
    ports:
      - "5435:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_SHARD}
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard2_primary_data:/bitnami/postgresql

  postgres_shard2_replica1:
    image: bitnami/postgresql:14
    container_name: postgres_shard2_replica1
    ports:
      - "5436:5432"
    depends_on:
      - postgres_shard2_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgres_shard2_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard2_replica1_data:/bitnami/postgresql

  postgres_shard2_replica2:
    image: bitnami/postgresql:14
    container_name: postgres_shard2_replica2
    ports:
      - "5437:5432"
    depends_on:
      - postgres_shard2_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgres_shard2_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - shard2_replica2_data:/bitnami/postgresql

  # ============ REDIS ============
  cache:
    image: redis:6.2-alpine
    container_name: redis-cache
    command: redis-server --save 20 1 --loglevel warning --requirepass password123
    environment:
      REDIS_PASSWORD: password123
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  # ============ MONGO ============
  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  # PostgreSQL
  shard1_primary_data:
  shard1_replica1_data:
  shard1_replica2_data:
  shard2_primary_data:
  shard2_replica1_data:
  shard2_replica2_data:

  # MySQL
  shard1_master_data:
  shard1_slave1_data:
  shard1_slave2_data:
  shard2_master_data:
  shard2_slave1_data:
  shard2_slave2_data:

  # Redis
  cache:

  # Mongo
  mongo_data:
